In [1]:
import numpy as np

In [2]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
arr = np.arange(11, 1)

In [5]:
arr

array([], dtype=int32)

In [6]:
arr = np.arange(start=1, stop=11)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.arange(stop=11, start=1)

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr = np.arange(1, 11, 2)

In [11]:
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.arange(start=1, stop=11, step=2)

In [13]:
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.arange(1, 11)

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [17]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [18]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9
