In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.shape

(10,)

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

0

In [6]:
arr[5]

5

In [7]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [8]:
arr[-1]

9

In [9]:
arr[-10]

0

In [10]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

In [11]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [12]:
arr2d.shape

(3, 4)

In [13]:
arr2d[0, 2]

3

In [14]:
arr2d[2, 1]

10

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[:5]

array([0, 1, 2, 3, 4])

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [21]:
arr2d[0, :]

array([1, 2, 3, 4])

In [22]:
arr2d[:, 2]

array([ 3,  7, 11])

In [23]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

In [25]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [26]:
idx = [1, 3, 5]

In [27]:
arr[idx]

array([23,  7, 65])

In [28]:
idx = [1, 3, 5]

In [29]:
arr[idx]

array([23,  7, 65])

In [30]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [31]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [34]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [35]:
myTrueFalse = [True, False, True]

In [36]:
arr[myTrueFalse]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [37]:
myTrueFalse = [True, False, True, False, True, False, True]

In [38]:
arr[myTrueFalse]

array([1, 3, 5, 7])

In [39]:
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [41]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])