In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [3]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [4]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [5]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [6]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [7]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
np.sum(a, axis=0)

array([3, 5, 7])

In [ ]:
np.sum(a, axis=1)

array([6, 9])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [ ]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
a - b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [9]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [10]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [11]:
a.shape, b.shape

((2, 3), (2, 3))

In [13]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [14]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [16]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [17]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [18]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [19]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [20]:
a.shape, b.shape

((3, 3), (3, 2))

In [21]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [22]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [23]:
1*1 + 2*3 + 3*5

22

In [24]:
1*2 + 2*4 + 3*6

28