In [1]:
import numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
mylist1 = [1, 2, 3, 4]

In [6]:
mylist2 = [[1, 2, 3, 4], 
           [5, 6, 7, 8]]

In [7]:
arr1 = np.array(mylist1)

In [8]:
arr2 = np.array(mylist2)

In [9]:
arr1.shape

(4,)

In [10]:
arr2.shape

(2, 4)

In [11]:
mylist = [1, 3.14, '테디', '1234']

In [12]:
mylist

[1, 3.14, '테디', '1234']

In [13]:
mylist[1]

3.14

In [14]:
mylist[2]

'테디'

In [15]:
arr = np.array([1, 2, 3, 3.14])

In [16]:
arr

array([1.  , 2.  , 3.  , 3.14])

In [17]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [18]:
arr

array([1, 2, 3, 3])

In [19]:
arr = np.array([1, 3.14, '테디', '1234'])

In [20]:
arr

array(['1', '3.14', '테디', '1234'], dtype='<U32')

In [21]:
arr[0] + arr[1]

'13.14'

In [22]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [23]:
arr

array([   1,    3, 1234])