In [2]:
import numpy as np

## 1. Broadcasting

## 1-1. 숫자의 연산 (단일)

In [3]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [4]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [6]:
# 코드를 입력해 주세요
a+b

array([[4, 5, 6],
       [5, 6, 7]])

In [7]:
# 코드를 입력해 주세요
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [8]:
# 코드를 입력해 주세요
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [9]:
# 코드를 입력해 주세요
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [10]:
# 코드를 입력해 주세요
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

### 1-2. array(배열)의 브로드캐스팅

오리지널 array의 shape가 유지됨을 잘 보세요

In [11]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [12]:
b = np.array([[1], 
              [2]])

In [13]:
a.shape, b.shape

((2, 3), (2, 1))

In [14]:
# 코드를 입력해 주세요
a * b

array([[1, 2, 3],
       [4, 6, 8]])

In [15]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [16]:
b = np.array([1, 2, 3])

In [17]:
# 코드를 입력해 주세요
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])