In [2]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

In [3]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [4]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [6]:
# 코드를 입력해 주세요
print(a + b)

[[4 6 8]
 [3 5 7]]


In [7]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [8]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [10]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### 1-2. Sum

In [12]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [16]:
# 코드를 입력해 주세요
np.sum(a,axis=0)

array([3, 5, 7])

In [17]:
# 코드를 입력해 주세요
np.sum(a,axis=1)

array([6, 9])

## 2. 행렬 - 뺄셈

In [18]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [19]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [29]:
# 코드를 입력해 주세요
print(np.subtract(a,b))

[[-2 -2 -2]
 [ 1  1  1]]


In [30]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [31]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [32]:
a - b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## 3. 곱셈

일반 곱셈

In [33]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [34]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [35]:
a.shape, b.shape

((2, 3), (2, 3))

In [36]:
# 코드를 입력해 주세요
print(np.multiply(a,b))

[[ 3  8 15]
 [ 2  6 12]]


단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [37]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [38]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [39]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [40]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [49]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [50]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [51]:
a.shape, b.shape

((3, 3), (3, 2))

In [53]:
# 코드를 입력해 주세요
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [54]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [46]:
1*1 + 2*3 + 3*5

22

In [47]:
1*2 + 2*4 + 3*6

28