In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
x = np.arange(10).reshape(-1,1) # reshape 코드입력
y = (2*x+1).reshape(-1,1) # reshape 코드입력

In [6]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

## 모델의 선언, fit(학습), predict(예측)

In [8]:
# 모델 선언
model = LinearRegression() # 코드입력

In [9]:
model

LinearRegression()

In [10]:
# 학습
model.fit(x,y) # 코드입력

LinearRegression()

In [11]:
# 예측
prediction = model.predict([[10.0]]) # 코드입력

In [12]:
prediction

array([[21.]])